### ISSUE TITLE
60% more production

### ISSUE THREAD

**Issue by nht1610** [encoderlee/OpenAlien#2]
![image](https://user-images.githubusercontent.com/17740340/187157773-f5fe0b1e-ac44-4271-8a32-778d75307b9c.png)

Hi, Encoderlee.
Can i ask you something?
did you know a about how to dig more 60% production, i know some group that they can do that, their noncethey generate different with my library.
Can you explain me how a nonce generate in your nonce.py.
Thank you for reading.
Best Regard.

**Comment by encoderlee** [comment]
increase production，we call it 'critical strike', it has nothing to do with 'nonce'.
 i known how to increase production, but it's a trade secret, no one will share  it publicly for free.
if it becomes public, It will definitely attract the attention of Alien Worlds project side.
nonce.py is from  the javascript code in  Alien Worlds official web page. 
I translated it into python code.

**Comment by nht1610** [comment]
Hi Encoderlee
Thank you for responding, you are so nice, there information help me so much, i was always think increase production by do something with 'nonce', i was stuck in that.
So can i buy solution increase production from you ?  How much does it cost ?
Thank you for helping.
Best Regard.

**Comment by encoderlee** [comment]
please leave your way to contact, such as the telegram username, I will contact you later.

**Comment by nht1610** [comment]
here is my telegam https://t.me/garfield0o

**Comment by nht1610** [comment]
Hi

**Comment by encoderlee** [comment]
its me

**Comment by encoderlee** [comment]
yes , i'm lee520 on telegram
