### ISSUE TITLE
Error use cpu_account

### ISSUE THREAD

**Issue by jakkapong1129** [encoderlee/OpenAlien#3]
![image](https://user-images.githubusercontent.com/60910772/195971893-ec53d851-99a0-4363-b9dd-660e87869e12.png)

**Comment by jakkapong1129** [comment]
im use anchor account

**Comment by encoderlee** [comment]
I need more error information in log file, this  KeyboardInterrupt exception is caused by your ctrl + c, I can't judge the cause of the error

**Comment by encoderlee** [comment]
now, the alien world official team has updated their smart contract, It prevents the act of paying by another account.
